In [ ]:
#Task6
#Q1
import numpy
inp = list(map(int, input().split()))
n = numpy.array(inp, float)
print(n)


1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
#Task6
#Q2
import numpy
inp = list(map(int, input().split()))
inar = numpy.array(inp)
print(numpy.reshape(inar, (3,3)))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Task6
#Q3
import numpy
inp = list(map(int, input().split()))
inp3 = []
n = inp[0]
for i in range(n):
  inp1 = list(map(int, input().split()))
  inp3.append(inp1)
inar = numpy.array(inp3)
print(numpy.transpose(inp3))
dis = inar.flatten()
print(dis)


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
#Task6
#Q4
import numpy
inp = list(map(int, input().split()))
ls1 = []
ls2 = []
for i in range(inp[0]):
  inp1 = list(map(int, input().split()))
  ls1.append(inp1)
for j in range(inp[1]):
  inp2 = list(map(int, input().split()))
  ls2.append(inp2)
arr1 = numpy.array(ls1)
arr2 = numpy.array(ls2)
print (numpy.concatenate((arr1, arr2), axis=0))




4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
#Task6
#Q5
import numpy
N = tuple(map(int, input().split()))
print (numpy.zeros(N, dtype = numpy.int)) 
print (numpy.ones(N, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
#Task6
#Q6
import numpy
numpy.set_printoptions(legacy='1.13')
n = list(map(int, input().split()))
print(numpy.eye(n[0], n[1], k=0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
#Task6
#Q7
import numpy
inp = list(map(int, input().split()))
ls1 = []
ls2 = []
for i in range(inp[0]):
  inp1 = list(map(int, input().split()))
  ls1.append(inp1)
for j in range(inp[0]):
  inp2 = list(map(int, input().split()))
  ls2.append(inp2)  
a = numpy.array(ls1)
b = numpy.array(ls2)  
print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(numpy.divide(a, b))
print(numpy.mod(a, b))
print(numpy.power(a, b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[ 0.2         0.33333333  0.42857143  0.5       ]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
#Task6
#Q8
import numpy
inp = list(map(float, input().split()))
arr = numpy.array(inp)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [ ]:
#Task6
#Q9
import numpy
inp = list(map(int, input().split()))
ls1 = []
for i in range(inp[0]):
  inp1 = list(map(int, input().split()))
  ls1.append(inp1)
arr1 = numpy.array(ls1) 
arr2 = numpy.sum(arr1, axis=0)
print(arr2)
print(numpy.prod(arr2)) 

2 2
1 2
3 4
[4 6]
24


In [ ]:
#Task6
#Q10
import numpy
inp = list(map(int, input().split()))
ls1 = []
for i in range(inp[0]):
  inp1 = list(map(int, input().split()))
  ls1.append(inp1)
arr1 = numpy.array(ls1)
arr2 = numpy.min(arr1, axis=1)
print(arr2)
print(numpy.max(arr2))  

4 2
2 5
3 7
1 3
4 0
[2 3 1 0]
3


In [ ]:
#Task6
#Q11
import numpy
inp = list(map(int, input().split()))
ls1 = []
for i in range(inp[0]):
  inp1 = list(map(int, input().split()))
  ls1.append(inp1)
arr1 = numpy.array(ls1)
print(numpy.mean(arr1, axis=1))
print(numpy.var(arr1, axis=0)) 
print(numpy.std(arr1, axis=None))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [ ]:
#Task6
#Q12
import numpy
N = int(input("Enter the number of rows and columns:"))
ls1 = []
ls2 = []
for i in range(N):
  inp1 = list(map(int, input().split()))
  ls1.append(inp1)
for j in range(N):
  inp2 = list(map(int, input().split()))
  ls2.append(inp2)
arr1 = numpy.array(ls1)
arr2 = numpy.array(ls2)
print(numpy.dot(arr1, arr2))  

Enter the number of rows and columns:2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
#Task6
#Q13
import numpy
inp1 = list(map(int, input().split()))
inp2 = list(map(int, input().split()))
arr1 = numpy.array(inp1)
arr2 = numpy.array(inp2)
print(numpy.inner(arr1, arr2))
print(numpy.outer(arr1, arr2))


0 1
2 3
3
[[0 0]
 [2 3]]


In [ ]:
#Task6
#Q14
import numpy
inp1 = list(map(float, input().split()))
arr1 = numpy.array(inp1)
print(numpy.roots(arr1))

1.1 2 3
[-0.90909091+1.37870463j -0.90909091-1.37870463j]


In [ ]:
#Task6
#Q15
import numpy
N = int(input("Enter the number of rows and columns:"))
ls1 = []
for i in range(N):
  inp1 = list(map(float, input().split()))
  ls1.append(inp1)
arr1 = numpy.array(ls1)
print(numpy.linalg.det(arr1))


Enter the number of rows and columns:2
1.1 1.1
1.1 1.1
0.0
